#!/bin/bash
set -euo pipefail

if [ ! -d ~/.ssh ]; then
        mkdir -m 700 ~/.ssh
fi

export http_proxy='http://proxy:3128'
export https_proxy='http://proxy:3128'

hn="$(echo $(hostname) | tr '[:upper]' '[:lower]')"   
echo "  Running on $(hostname)"
if [ "${hn:0:2}" = "vm" ]; then
	userQ=".all[]? , .vms[]? , .\"$hn\"[]? "
	echo "  VM Instance found!"
else 
	userQ=".all[]? , .\"$hn\"[]? "
	echo "  Non VM Instance found!"
fi
# echo $userQ
curl -sS https://rgt-tools.duckdns.org/drive/api/public/dl/JzcWHOIA/plataforma/vm-users.json | tr '[:upper:]' '[:lower:]' | jq -r "$userQ" | sort | uniq  > ~/.ssh/users

if [ -f ~/.ssh/authorized_keys ]; then
        cat  ~/.ssh/authorized_keys > ~/.ssh/gh_keys
fi

echo "  Including keys on authorized keys for:"
while read u; do
        if [ ! -z "$u" ]; then
        		echo "    - $u"
                curl -sS "https://github.com/$u.keys" >> ~/.ssh/gh_keys
        fi
done <~/.ssh/users

sort ~/.ssh/gh_keys | grep '^ssh*' | uniq > ~/.ssh/authorized_keys

if [ -f ~/.ssh/gh_keys ]; then
         rm ~/.ssh/gh_keys
fi
