---
  - name : Install default packages
    become: yes  
    apt: 
      pkg:
        - git
        - wget
        - unzip
        - jq
        - telnet
        - curl
        - htop
        - lm-sensors
        - python3
        - python3-pip
        - cifs-utils
        - cmatrix
      state: latest
      update_cache: yes   

  - name : Update packages
    become: yes  
    apt: name="*" state=latest update_cache=true force_apt_get=true

  - name: Update system - fix broken install
    become: yes
    command: apt-get --fix-broken install -y

  - name: Update system - update apt
    become: yes
    command: apt-get update -y
    
  - name: Update system- dist-upgrade
    become: yes
    command: apt-get dist-upgrade -y
    
  - name: Update system - full-upgrade
    become: yes
    command: apt-get full-upgrade -y
    
  - name: Update system - autoclean
    become: yes
    command: apt-get autoclean -y
  
  - name: Update system - autoremove
    become: yes
    command: apt-get autoremove -y