serverAddr = "127.0.0.1"
serverPort = 7000

[[proxies]]
name = "test-tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000

/srv/frp [ubuntu@vm-proxy] [0:28]
> cat frps.toml
bindPort = 443
vhostHTTPPort = 80
log.to = "/srv/frp/frps.log"
log.maxDays = 3

detailedErrorsToClient = true

auth.method = "token"
auth.token = "SUPERSECRETUPPERTOKEN"