---
  servers: 
    - { server: c6-router, ip: 192.168.0.011 }
    - { server: c7-router, ip: 192.168.0.010 }
    - { server: fino-note-cable, ip: 192.168.0.021 }
    - { server: fino-note, ip: 192.168.0.022 }
    - { server: odroid-a, ip: 192.168.0.0101 }
    - { server: odroid-b, ip: 192.168.0.106 }
    - { server: pepe-note, ip: 192.168.0.023 }
    - { server: raspw, ip: 192.168.0.122 }
    - { server: rasp2, ip: 192.168.0.103 }
    - { server: rasp3, ip: 192.168.0.102 }
    - { server: rasp3w,ip: 192.168.0.121 }
    - { server: rasp4, ip: 192.168.0.100 }
    - { server: rasp4w, ip: 192.168.0.120 }
    - { server: rgt-cel, ip: 192.168.0.050 }
    - { server: tablet, ip: 192.168.0.051 }
    - { server: vivo, ip: 192.168.0.001 }
    - { server: vostro-01, ip: 192.168.0.026 }
    - { server: vostro-02, ip: 192.168.0.027 }
    - { server: x79, ip: 192.168.0.025 }
    - { server: xbox-one, ip: 192.168.0.035 }
    - { server: xbox-sx, ip: 192.168.0.036 }
    - { server: xps, ip: 192.168.0.019 }
    - { server: xpsw, ip: 192.168.0.020 }