---
  - name: Install tmux
    become: yes
    apt: name=tmux state=latest update_cache=true
    
  - name: Check if tmux path exists
    stat:
      path: "~/.tmux"
    register: result      
    
  - name: Clone oh-my-tmux repo
    command: git clone --depth=1 https://github.com/gpakosz/.tmux.git ~/.tmux
    args:
      chdir: ~
    when: not result.stat.exists

  - name: Create a link to config file
    command: ln -s -f .tmux/.tmux.conf
    args:
      chdir: ~
    when: not result.stat.exists

  - name: Copy config file
    command: cp .tmux/.tmux.conf.local .
    args:
      chdir: ~
    when: not result.stat.exists      