---
  - name: Check if micro path exists
    stat:
      path: "/usr/bin/micro"
    register: result
    
  - name: Get install script
    get_url:
      url: https://getmic.ro
      dest: /tmp/install-micro.sh
    when: not result.stat.exists

  - name: Change Install micro editor script perm
    become: yes
    file:
      path: /tmp/install-micro.sh
      mode: u+rwx,g+rx,o+rwx    
    when: not result.stat.exists 

  - name: Execute install micro editor script
    become: yes
    command: /tmp/install-micro.sh
    when: not result.stat.exists

  - name: Remove micro editor install script
    become: yes
    file:
      path: /tmp/install-micro.sh
      state: absent 
    when: not result.stat.exists    

  - name: Move micro editor binary to common folder
    become: yes
    command: sudo mv micro /usr/bin
    args:
      chdir: /tmp
    when: not result.stat.exists      