--- 
  - name: Install GIT
    become: yes
    apt: name=git state=latest update_cache=true

  - name: Clone powerline fonts repo
    command: git clone --depth=1 https://github.com/powerline/fonts.git
    args:
      chdir: ~

  - name: Install powerlines fonts
    command: ./fonts/install.sh
    args:
      chdir: ~

  - name: Remove powerlines fonts temp repo
    command: rm -rf fonts
    args:
      chdir: ~

  - name: Clone nerd fonts repo
    command: git clone --depth=1 https://github.com/ryanoasis/nerd-fonts.git
    args:
      chdir: ~

  - name: Install nerd fonts
    command: ./nerd-fonts/install.sh
    args:
      chdir: ~

  - name: Remove nerd fonts temp repo
    command: rm -rf nerd-fonts
    args:
      chdir: ~        
    